### ISSUE TITLE
Provide ability to choose between public and private clusters

### ISSUE THREAD

**Issue by hyder** [oracle/cluster-api-provider-oci#16]
**What would you like to be added**:

Currently, clusters created by CAPOCI can all be publicly accessed via a public load balancer. This issue is a proposal to make it possible to have clusters whose API servers can only be accessed via a restricted CIDR range and not exposed to the Internet.

**Why is this needed**:
Restricting public access to Kubernetes clusters is recommended in order to improve the security level of a Kubernetes cluster.

**Comment by shyamradhakrishnan** [comment]
@hyder right now, CAPOCI LoadBalancer is private or public based on the Control plane Endpoint Subnet. So if the Subnet is Private, the load balancer is private. Is this what you were expecting? 
What we are missing in this case is to peer management cluster and workload cluster VCN so that management cluster can talk to workload cluster.
