### ISSUE TITLE
Add ability to skip management of VCN components

### ISSUE THREAD

**Issue by shyamradhakrishnan** [oracle/cluster-api-provider-oci#225]
**What would you like to be added**:
Add ability to skip management of VCN components

Users should have ability to selectively create/manage the following components in the case where CAPOCI is managing VCN.

- Internet Gateway
- NAT Gateway
- Route Table
- NSG
- Seclist

Currently CAPOCI takes a brute force approach here. For example if there is a public subnet, it creates an Internets Gateway. This has to be changed such that users have ability to specify if they want to create the component.

**Why is this needed**:

In certain cases, users want the ability manage these at individual level.

**Comment by mattiaforc** [comment]
When was this released? I tried to make a clean install of OCI CAPI v0.8.1, but it seems I can't find these "skip" parameters (nor the infrastructure.cluster.x-k8s.io/v1beta1 CRD).

**Comment by joekr** [comment]
I believe it is a part of `v1beta2` api

**Comment by shyamradhakrishnan** [comment]
@mattiaforc the flag you are using has not been released as pointed out by @joekr . Can you come over to #cluster-api-oci channel in kubernetes slack and tell us what your usecase is and what timelime you are looking for if you want to use the latest flag? We are hoping to have the release by mid to end may, but would like to understand your requirements to make sure that we will meet them. We can discuss here as well if you prefer that.

**Comment by mattiaforc** [comment]
@joekr Thanks for pointing it out! I guess I'll wait for the next release.

@shyamradhakrishnan Sure, I'll explain briefly what I'm trying to accomplish, but it's not a big deal actually :) 

I'm digging into the CAPI topic, and I am evaluating differente infrastructure providers by making small POCs (proof of concepts), as simple as possible. Regarding Oracle Cloud, I am experimenting only with the Always-free tier resources; I already had deployed a small Kubernetes cluster with them but via Terraform - so this time I wanted to try the declarative/GitOps approach, and I (and this is probably due to my lack of knowledge) stumbled upon some limitations, like the NAT Gateway that can't be created in always-free, and possibly other stuff (I saw in the CAPI controller manager some logs about the impossibility of creating multiple LB... but I don't see those logs anymore)

I am simply trying to recreate the same small setup I had with Terraform, because I like the portability of the CAPI design, that's all :)

**Comment by shyamradhakrishnan** [comment]
@mattiaforc there is a template in our repo which creates cluster in free tier(https://github.com/oracle/cluster-api-provider-oci/blob/release-v0.8.0/templates/cluster-template-arm-free-tier.yaml), but unfortunately gets stuck in the VM image part, as free tier does not support custom VM images. So you will have to hack the pre kubeadm commands to install the necessary software. We may be able to add built in support for free tier in few months, but too early to comment on that,
